project:
  type: book
  resources: static/*
  output-dir: ../_docs
  # pre-render: 
  # post-render:
 
book:
  title: "ECHILD documentation"
  reader-mode: true

  # cover-image: cover.jpg
  favicon: favicon.ico
  site-url: https://docs.echild.ac.uk/
  repo-url: https://github.com/UCL-ECHILD/docs.echild.ac.uk-website
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

    - intro.qmd

    - part: part1.qmd
      chapters:
        - part1a.qmd
        - part1b.qmd

    - part: part2.qmd
      chapters:
        - part2a.qmd
        - EDA.qmd

format:
  html:
    theme:
      - cosmo
    code-copy: true
    code-link: true
    